USE hr;
-- atividade 1
SELECT MAX(SALARY) AS MAIOR_SALARIO FROM employees;
-- atividade 2
SELECT MAX(SALARY) - MIN(SALARY) AS DIFERENTE FROM employees;
-- atividade 3
SELECT  JOB_ID, AVG(SALARY) AS 'MEDIA_SALARIAL'
FROM employees
GROUP BY JOB_ID
ORDER BY `MEDIA_SALARIAL` DESC;

