use PiecesProviders;

SELECT * FROM Provides WHERE PROVIDER = 'RBT';
SELECT * FROM Provides ORDER BY Price DESC LIMIT 5;
SELECT * FROM Provides ORDER BY Price DESC LIMIT 4 OFFSET 3;
SELECT * FROM Provides WHERE PROVIDER = 'HAL' ORDER BY PRICE DESC;
SELECT * FROM Provides WHERE Piece = '1';